name: Fetch Tullverket Codes

on:
  workflow_dispatch:  # run manually

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: pip install -r scripts/requirements.txt

      - name: Run fetch_tullverket_codes.py
        run: python scripts/fetch_tullverket_codes.py
